

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t43-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api43.my-points.ru
    - web43.my-points.ru
    - insights43.my-points.ru
    secretName: serverpod-tls-t43
  rules:
  - host: "api43.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t43-server-service
            port:
              name: api
  - host: "web43.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t43-server-service
            port:
              name: web
  - host: "insights43.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t43-server-service
            port:
              name: insights
    